spring.application.name=taskpilot-backend

# Database Configuration (Reads from Environment variables in production, falls back to local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskpilot_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:119088}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Run schema.sql before Hibernate starts to ensure new columns exist
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.jpa.defer-datasource-initialization=true

# JWT Secret (In production, inject via env variables)
app.jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
app.jwt.expiration-milliseconds=86400000

# Groq AI Configuration
groq.api.key=${GROQ_API_KEY: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}

# Email Server Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=taskpilotauth@gmail.com
spring.mail.password=gzcy iegz iihy tsmy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth Configuration
spring.security.oauth2.client.registration.google.client-id=759293200220-bdr3pls4l7kp3j4sjeapi6erlhn8186h.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
server.port=${PORT:8080}

# Razorpay Configuration
razorpay.key.id=rzp_test_SQlc4H3sw5qVmY
razorpay.key.secret=8ydFEt3p0AL5IBd883u99JfT
razorpay.webhook.secret=Za6VEsUPnnU_aWy
